# Версия docker-compose
version: '2'
# Список наших сервисов (контейнеров)
services:
    nginx:
        container_name: nginx
        # используем последний стабильный образ nginx
        image: nginx:latest
        # маршрутизируем порты
        ports:
            - "8088:80"
            - "443:443"
        # монтируем директории, слева директории на основной машине, справа - куда они монтируются в контейнере
        volumes:
            - ./docker/hosts:/etc/nginx/conf.d
            - ./www:/var/www
            - ./logs:/var/log/nginx
            - ./docker/certs:/etc/nginx/ssl
        # nginx должен общаться с php контейнером
        links:
            - php
    php:
        container_name: php
        # у нас свой образ для PHP, указываем путь к нему и говорим что его надо собрать
        build: ./images/php
        # этот образ будет общаться с mysql
        links:
            - mysql
        # монтируем директорию с проектами
        volumes:
            - ./www:/var/www
    mysql:
        container_name: databases
        image: mysql:8
        ports:
            - "3306:3306"
        volumes:
            - ./mysql:/var/lib/mysql
        # задаем пароль для root пользователя
        environment:
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel@%
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret
        command: '--default_authentication_plugin=mysql_native_password'
